# Checks that a PR has a changeset, or that the description
# explicitly says "no changeset needed".

name: Check that PR has a changeset

on:
  pull_request:
    branches: [$default-branch]

jobs:
  check-if-changeset:
    name: Check that PR has a changeset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const pullNumber = context.issue.number;

            console.log("check if an added file is in the .changeset directory")
            const { data: files } = await github.rest.pulls.listFiles({
              ...context.issue,
              pull_number: pullNumber
            });

            const changeset = files.find(
              file => file.status === "added" && file.filename.startsWith(".changeset/")
            );

            if (changeset !== undefined) {
              console.log("Changeset found:", changeset.filename);
              return;
            }

            console.log('check if the PR description says "no changeset needed"')
            const { data: pull } = await github.rest.pulls.get({
              ...context.issue,
              pull_number: pullNumber
            });

            const noChangesetNeededComment = pull.body
              ?.toLowerCase()
              .includes("no changeset needed");

            if (noChangesetNeededComment) {
              console.log("The PR description says that no changeset is needed");
              return;
            }

            console.error("No changeset found");
            process.exit(1);
