# Checks that a PR has a changeset, or that someone explicitly added a comment
# saying "no changeset needed".

name: Check changeset

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Check that PR has a changeset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
      - name: Search comment saying that a changeset was added
        uses: peter-evans/find-comment@v2
        id: search_changeset_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: Changeset detected
      - name: Search comment saying that a changeset is not needed
        uses: peter-evans/find-comment@v2
        id: search_no_changeset_needed
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: no changeset needed
      - name: Check changeset
        run: test -n "${{ steps.search_changeset_comment.outputs.comment-id }}" || test -n "${{ steps.search_no_changeset_needed.outputs.comment-id }}"
