name: Lint

on:
  push:
    branches: [pre-release-testing-branch]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  pre_release_checks:
    name: Pre-release checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: yarn
      - name: Install
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn build
      - name: lint
        run: yarn lint
      - name: test
        run: yarn test
      - name: Check dependency versions
        run: node scripts/check-dependencies.js
